### ISSUE TITLE
PackagesNotFoundError: The following packages are not available from current channels

### ISSUE THREAD

**Issue by juuliaholz** [conda-forge/graph-tool-feedstock#108]
Hi, 

I am trying to install the graph tool package via conda. I already created a new environment and added the conda forge channels. 

But whenever I try to install the package with `conda install -c conda-forge graph-tool` I receive the following error: 

PackagesNotFoundError: The following packages are not available from current channels:

  - graph-tool

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by stuarteberg** [comment]
Please tell us about your platform and conda installation by running the following commands and pasting the output into this thread:

```bash
conda info
```

and

```bash
conda list
```

(Ideally, place the output in a `<details></details>` block to avoid cluttering this page.)
