### ISSUE TITLE
Stuck at Solving the Environment

### ISSUE THREAD

**Issue by gkrish19** [conda-forge/graph-tool-feedstock#14]
Issue: The conda installation is stick at solving the environment part and not going further. 

<br/>
Environment (<code>conda list</code>):
<details>
Anaconda 3.5.2, Python 3.6.5, Platform: Linux (ubuntu)
```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by stuarteberg** [comment]
I recommend creating an environment from scratch for graph-tool only, and then installing other packages to it one-by-one, if you need them. 

```
conda create -n gt -c conda-forge graph-tool
conda activate gt

# Additional packages
conda install ipython
conda install jupyterlab
```

**Comment by count0** [comment]
@stuarteberg Could you please put this in the README.md as the recommend way of installing? Proceeding in the standard way from a clean anaconda install results in a stuck environment solving...

**Comment by stuarteberg** [comment]
>Could you please put this in the README.md as the recommended way of installing?

OK, as you saw, I created and merged #17 for this, but I think the feedstock readme is not the ideal location for these instructions:

1. The feedstock README is auto-generated, so I think it will be overwritten the next time this recipe needs to be re-rendered.
2. I suspect most conda users are unaware of the existence of feedstock repos, and are unlikely to inspect the feedstock README for guidance.

I think the ideal place for these instructions is the [graph-tool documentation itself][1].  Perhaps you can paste the new text into those docs?

**Comment by count0** [comment]
Yes, I will do that.

**Comment by stuarteberg** [comment]
Minor side note: To be technically correct, the docs should say that it's possible to install `graph-tool` via `conda`, not "Anaconda".

`conda` is the package manager, whereas Anaconda and conda-forge are each distributions that both happen to use that package manager.  (Somewhat analogous to RedHat and CentOS -- both use RPM, but they are distinct distributions.  Anaconda packages and conda-forge packages can sometimes be mixed without trouble but I don't recommend it.)

Our graph-tool package is part of the conda-forge distribution, not the Anaconda distribution.

**Comment by count0** [comment]
I guess it's obvious at this point that I'm not an avid (ana)conda user. :-)

Thanks for the correction; I've updated the documentation!

**Comment by stuarteberg** [comment]
@gkrish19 -- Hopefully the instructions above worked for you.  If not, reopen this issue and provide the output of `conda info` and `conda list`, as well as the exact commands you tried (and their output).

**Comment by gkrish19** [comment]
Thank you for your help. It works now.
