### ISSUE TITLE
graph-tool installation via conda not working 

### ISSUE THREAD

**Issue by stephwon** [conda-forge/graph-tool-feedstock#144]
### Comment:

I used below commands to install graph tool but it's giving me `ModuleNotFoundError: No module named 'graph_tool'` error message when I do `import graph_tool.all as gt`
`conda create --name gt -c conda-forge graph-tool`
`conda activate gt`

conda is in the latest version, up to date. How can I address this issue?

**Comment by stuarteberg** [comment]
What OS are you using? Can you provide the output of the conda commands you are running?

**Comment by stuarteberg** [comment]
Also provide the output of “conda --info”, please.

**Comment by pacificoceanmist** [comment]
```
active environment : base
    active env location : /scratch/user/anaconda3
            shell level : 1
       user config file : /home/user/.condarc
 populated config files : /home/user/.condarc
          conda version : 23.7.4
    conda-build version : 3.26.1
         python version : 3.11.5.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=12.4=0
                          __glibc=2.35=0
                          __linux=5.15.0=0
                          __unix=0=0
       base environment : /scratch/user/anaconda3  (writable)
      conda av data dir : /scratch/user/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /scratch/user/anaconda3/pkgs
                          /home/user/.conda/pkgs
       envs directories : /scratch/user/anaconda3/envs
                          /home/user/.conda/envs
               platform : linux-64
             user-agent : conda/23.7.4 requests/2.31.0 CPython/3.11.5 Linux/5.15.0-107-generic ubuntu/22.04.4 glibc/2.35 aau/0.4.2 c/AzXW8LigKWlDxTADFvRs4A s/0nHj0vA62XCZwqrEX-H7Nw e/NtKMpYYuakPq65NqOuBpBQ
                UID:GID : 5527037:50006
             netrc file : None
           offline mode : False
```
@stuarteberg running on Ubuntu 22.04.4 LTS using Mac

**Comment by pacificoceanmist** [comment]
I just tried `conda install conda-forge::graph-tool`, and it's stuck at `Solving environment`....

**Comment by stuarteberg** [comment]
Did you activate the `gt` environment after you created it?  Run `conda activate gt` and then check the output of `type python`.  If the environment was properly activated and `graph-tool` still isn't working, then proceed with the instructions below.

---

Your version of `conda` is slightly out-of-date.  Just to make sure we're on the same page, try updating:

```bash
conda install -n base 'conda>=24.5.0'
```

And then try installing `graph-tool-base` with the following command:

```bash
conda create -n gt --override-channels -c conda-forge 'graph-tool-base>=2.68'
```

And check to see if it was installed properly:

```bash
conda activate gt
python -c 'import graph_tool.all as gt'
```

If that works, you can try installing the full `graph-tool` package (which includes drawing dependencies).

```bash
conda install -n gt --override-channels -c conda-forge `graph-tool>=2.68`
```

**Comment by stuarteberg** [comment]
>running on Ubuntu 22.04.4 LTS using Mac

Linux on a Mac?  Are you running in a Docker container?  That should work fine, though I'm not certain about the drawing features in that case.

**Comment by HoldenN7** [comment]
I'm having the same issue on MacOS. Even after following the instructions you posted above I still get a moduleNotFound error.

**Comment by stuarteberg** [comment]
@HoldenN7 please paste the output of “conda info” here, as well as the transcript of output you see when following the commands above.
