### ISSUE TITLE
Can not install 

### ISSUE THREAD

**Issue by raviolli** [conda-forge/graph-tool-feedstock#21]
Issue:
 When I try to install using conda it fails.
When I install graph-tool it also install 2.29 and I need 2.32.
<br/>
Environment (<code>conda list</code>):
<details>
Conda install graph-tool=2.32
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by stuarteberg** [comment]
Please try the instructions on the graph-tool website:
https://git.skewed.de/count0/graph-tool/-/wikis/installation-instructions#conda

If something goes wrong, respond to this thread with the commands you tried and also the error messages you see.

**Comment by raviolli** [comment]
(py3env) tait-dev-0@taitlocal0-MS-7693:~/src/nervosa-dev/nervosa/phrases/vector_text_compression$ conda install graph-tool=2.32
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                                                       
                                                                                                                                                                                                             
UnsatisfiableError: The following specifications were found to be incompatible with each other:                                                                                                              



Package atk-1.0 conflicts for:
graph-tool=2.32 -> gtk3 -> atk[version='>=2.32.0,<3.0a0'] -> atk-1.0=2.36.0
graph-tool=2.32 -> matplotlib-base -> atk-1.0[version='>=2.36.0']
Package tk conflicts for:
pycparser==2.19=py_0 -> python -> tk[version='8.5.*|8.6.*|8.5.18|>=8.6.10,<8.7.0a0|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0|>=8.6.9,<8.7.0a0']
python_abi -> python=3.7 -> tk[version='8.5.*|8.6.*|8.5.18|>=8.6.10,<8.7.0a0|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0|>=8.6.9,<8.7.0a0']
cryptography==2.3.1 -> python[version='>=2.7,<2.8.0a0'] -> tk[version='8.5.*|8.6.*|8.5.18|>=8.6.10,<8.7.0a0|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0|>=8.6.9,<8.7.0a0']
boto==2.49.0 -> python[version='>=3.7,<3.8.0a0'] -> tk[version='8.5.*|8.6.*|8.5.18|>=8.6.10,<8.7.0a0|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0|>=8.6.9,<8.7.0a0']
mkl-service==2.3.0 -> python[version='>=2.7,<2.8.0a0'] -> tk[version='8.5.*|8.6.*|8.5.18|>=8.6.10,<8.7.0a0|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0|>=8.6.9,<8.7.0a0']
python=3.7.6 -> tk[version='>=8.6.10,<8.7.0a0|>=8.6.8,<8.7.0a0']
pyopenssl==19.0.0 -> python[version='>=3.8,<3.9.0a0'] -> tk[version='8.5.*|8.6.*|8.5.18|>=8.6.10,<8.7.0a0|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0|>=8.6.9,<8.7.0a0']
tk==8.6.8
smart_open==1.9.0=py_0 -> python -> tk[version='8.5.*|8.6.*|8.5.18|>=8.6.10,<8.7.0a0|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0|>=8.6.9,<8.7.0a0']
python-dateutil==2.8.1=py_0 -> python -> tk[version='8.5.*|8.6.*|8.5.18|>=8.6.10,<8.7.0a0|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0|>=8.6.9,<8.7.0a0']
bz2file==0.98 -> python -> tk[version='8.5.*|8.6.*|8.5.18|>=8.6.10,<8.7.0a0|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0|>=8.6.9,<8.7.0a0']
urllib3==1.25.8 -> python[version='>=3.7,<3.8.0a0'] -> tk[version='8.5.*|8.6.*|8.5.18|>=8.6.10,<8.7.0a0|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0|>=8.6.9,<8.7.0a0']
setuptools==45.1.0 -> python[version='>=3.7,<3.8.0a0'] -> tk[version='8.5.*|8.6.*|8.5.18|>=8.6.10,<8.7.0a0|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0|>=8.6.9,<8.7.0a0']
requests==2.22.0 -> python[version='>=3.6,<3.7.0a0'] -> tk[version='8.5.*|8.6.*|8.5.18|>=8.6.10,<8.7.0a0|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0|>=8.6.9,<8.7.0a0']
asn1crypto==1.3.0 -> python[version='>=3.8,<3.9.0a0'] -> tk[version='8.5.*|8.6.*|8.5.18|>=8.6.10,<8.7.0a0|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0|>=8.6.9,<8.7.0a0']
cffi==1.13.2 -> python[version='>=3.8,<3.9.0a0'] -> tk[version='8.5.*|8.6.*|8.5.18|>=8.6.10,<8.7.0a0|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0|>=8.6.9,<8.7.0a0']
chardet==3.0.4 -> python[version='>=3.7,<3.8.0a0'] -> tk[version='8.5.*|8.6.*|8.5.18|>=8.6.10,<8.7.0a0|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0|>=8.6.9,<8.7.0a0']
pip==20.0.2 -> python[version='>=3.8,<3.9.0a0'] -> tk[version='8.5.*|8.6.*|8.5.18|>=8.6.10,<8.7.0a0|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0|>=8.6.9,<8.7.0a0']
boto3==1.11.0=py_0 -> python -> tk[version='8.5.*|8.6.*|8.5.18|>=8.6.10,<8.7.0a0|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0|>=8.6.9,<8.7.0a0']
mkl_random==1.1.0 -> python[version='>=3.7,<3.8.0a0'] -> tk[version='8.5.*|8.6.*|8.5.18|>=8.6.10,<8.7.0a0|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0|>=8.6.9,<8.7.0a0']
wheel==0.34.1 -> python[version='>=3.6,<3.7.0a0'] -> tk[version='8.5.*|8.6.*|8.5.18|>=8.6.10,<8.7.0a0|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0|>=8.6.9,<8.7.0a0']
scipy==1.4.1 -> python[version='>=3.6,<3.7.0a0'] -> tk[version='8.5.*|8.6.*|8.5.18|>=8.6.10,<8.7.0a0|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0|>=8.6.9,<8.7.0a0']
gensim==3.8.0 -> python[version='>=3.6,<3.7.0a0'] -> tk[version='8.5.*|8.6.*|8.5.18|>=8.6.10,<8.7.0a0|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0|>=8.6.9,<8.7.0a0']
mkl_fft==1.0.15 -> python[version='>=3.7,<3.8.0a0'] -> tk[version='8.5.*|8.6.*|8.5.18|>=8.6.10,<8.7.0a0|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0|>=8.6.9,<8.7.0a0']
s3transfer==0.3.0 -> python[version='>=3.7,<3.8.0a0'] -> tk[version='8.5.*|8.6.*|8.5.18|>=8.6.10,<8.7.0a0|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0|>=8.6.9,<8.7.0a0']
botocore==1.14.0=py_0 -> python -> tk[version='8.5.*|8.6.*|8.5.18|>=8.6.10,<8.7.0a0|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0|>=8.6.9,<8.7.0a0']
numpy-base==1.18.1 -> python[version='>=3.8,<3.9.0a0'] -> tk[version='8.5.*|8.6.*|8.5.18|>=8.6.10,<8.7.0a0|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0|>=8.6.9,<8.7.0a0']
jmespath==0.9.4=py_0 -> python -> tk[version='8.5.*|8.6.*|8.5.18|>=8.6.10,<8.7.0a0|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0|>=8.6.9,<8.7.0a0']
numpy==1.18.1 -> python[version='>=3.7,<3.8.0a0'] -> tk[version='8.5.*|8.6.*|8.5.18|>=8.6.10,<8.7.0a0|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0|>=8.6.9,<8.7.0a0']
six==1.14.0 -> python[version='>=3.6,<3.7.0a0'] -> tk[version='8.5.*|8.6.*|8.5.18|>=8.6.10,<8.7.0a0|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0|>=8.6.9,<8.7.0a0']
pysocks==1.7.1 -> python[version='>=3.8,<3.9.0a0'] -> tk[version='8.5.*|8.6.*|8.5.18|>=8.6.10,<8.7.0a0|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0|>=8.6.9,<8.7.0a0']
docutils==0.15.2 -> python[version='>=3.6,<3.7.0a0'] -> tk[version='8.5.*|8.6.*|8.5.18|>=8.6.10,<8.7.0a0|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0|>=8.6.9,<8.7.0a0']
idna==2.8 -> python[version='>=3.8,<3.9.0a0'] -> tk[version='8.5.*|8.6.*|8.5.18|>=8.6.10,<8.7.0a0|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0|>=8.6.9,<8.7.0a0']
certifi -> python[version='>=3.6,<3.7.0a0'] -> tk[version='8.5.*|8.6.*|8.5.18|>=8.6.10,<8.7.0a0|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0|>=8.6.9,<8.7.0a0']
Package gtk3 conflicts for:
graph-tool=2.32 -> gtk3

**Comment by stuarteberg** [comment]
Right, it's not surprising that you can't install `graph-tool` to an existing environment.  It has many dependencies, and some of them may not be compatible with the packages you have already installed.  The best way forward is to create a new environment, and then try installing your other packages to it, perhaps even one at a time.  You may discover which one is causing the incompatibility, and then decide what to do about it.

Please try the instructions I linked to above, and report here if you run into errors.

```
conda create --name gt -c conda-forge graph-tool
conda activate gt

conda install <other packages you need>
```

**Comment by raviolli** [comment]
Yes. I understand. Thank you I shall do that.
