### ISSUE TITLE
Provide a base package without drawing dependencies

### ISSUE THREAD

**Issue by stuarteberg** [conda-forge/graph-tool-feedstock#28]
Many of the dependencies of our `graph-tool` package are solely to provide drawing support.  (They are [listed in the graph-tool documentation][1].)  Since most of graph-tool's features do not require drawing, it may be useful (for multiple reasons) to offer a smaller package for users who don't need drawing.  This is easily supported in conda recipes.  The [`matplotlib` feedstock][2] serves as an example.  So, in our case, our recipe would emit two packages: `graph-tool-base`,  and `graph-tool`.

[1]: https://git.skewed.de/count0/graph-tool/-/wikis/installation-instructions#manual-compilation
[2]: https://github.com/conda-forge/matplotlib-feedstock/blob/master/recipe/meta.yaml

**Comment by count0** [comment]
Would it be strictly necessary to split the package? Wouldn't it be sufficient to list pycairo, gtk and matplotlib as optional dependencies?

**Comment by stuarteberg** [comment]
That's possible, but the "conda-forge way" is typically to include all dependencies out-of-the-box.  A typical user (who hasn't read the documentation) will get everything they need.  More sophisticated users (e.g. compute cluster or cloud users), may appreciate the option to omit the dependencies they don't need.  They'll have to read the documentation to discover this option, though.

**Comment by count0** [comment]
It does makes perfect sense for it to be "opt out" instead of "opt in".

**Comment by stuarteberg** [comment]
Closed via #57.

**Comment by stuarteberg** [comment]
Apparently our `graph-tool-base` package now depends on `cairo` and `cairomm-1.0` (a special package that enforces ABI compatibility, I think).

I believe that's happening because those packages happen to be installed in the `host` section during the base build, so they can influence the base dependencies through their own `run_exports` specifications.  We can eliminate those via `ignore_run_exports` as [described in the conda-forge docs][1].

[1]: https://conda-forge.org/docs/maintainer/pinning_deps.html#globally-pinned-packages

Re-opening this issue, since the "base" package is no longer free of drawing dependencies.

<img width="243" alt="image" src="https://user-images.githubusercontent.com/1655821/128644860-7a863284-60c1-454e-a1d3-8f4aff3c513e.png">
