### ISSUE TITLE
Maintainers

### ISSUE THREAD

**Issue by stuarteberg** [conda-forge/graph-tool-feedstock#4]
Good news!  Thanks to this year's improvements to conda-forge's infrastructure (e.g. C++17 compilers, longer build times), it has become feasible to maintain a conda-forge feedstock for `graph-tool`.  So here we are.

Is anyone else interested in helping me maintain this package?  If so, let me know and I'll add you to the [maintainers list][2], which will automatically give you commit permissions to this feedstock.

[2]: https://github.com/conda-forge/graph-tool-feedstock/blob/d4154c6ce185d14073b639068adb760c6f273d0b/recipe/meta.yaml#L89

@ostrokach, [you've maintained your own recipe][3] for some time now.  Care to help out with this one?

[3]: https://gitlab.com/ostrokach-forge/graph-tool

And of course, if the man himself wants to help out, that would be great.  So, any interest, @count0?

**Comment by count0** [comment]
This sounds interesting indeed, I'd be happy to contribute.

@ostrokach, nice to have you on board as well!
