### ISSUE TITLE
What is the final solution to install graph-tool in an already conda env?

### ISSUE THREAD

**Issue by JohannHM** [conda-forge/graph-tool-feedstock#47]
- [ ] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue: For so many ways I've tried to install graph-tool in an environment I've been worked, and it has been impossible. I've tryed these:
1.  conda install -c conda-forge graph-tool 
2.  conda install -c conda-forge/label/cf202003 graph-tool 
3. conda config --add channels conda-forge
    conda install graph-tool

I'm not interested to create another env, so Is it possible to use graph-tool without create another env?
Thanks in advance.
<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by stuarteberg** [comment]
In principle it should be possible, but in practice there are many dependencies which can conflict.  You may be better off creating an environment for graph-tool and installing your additional packages to it one-by-one to understand where the problem lies.

**Comment by JohannHM** [comment]
Thanks for your recommendation!
