### ISSUE TITLE
Cannot install graph-tool

### ISSUE THREAD

**Issue by kookcutie97** [conda-forge/graph-tool-feedstock#87]
### Comment:

Hello,

I am currently trying to install graph-tool in my Anaconda environment and keep running into errors.

As suggested, I have tried to create a new environment and installed graph-tool using the following command:
**conda create --name gt -c conda-forge graph-tool**

However, I receive the following error:

Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - graph-tool

Current channels:

  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

Please let me know if I am missing anything?

**Comment by stuarteberg** [comment]
Sorry, graph-tool is not available for windows.
